export { arrayEqual } from './arrayEqual';
export { getCookie, setCookie, removeCookie } from './cookie';
export { getBrowserInfo } from './device';
export { formatFloat } from './formatFloat';
export { formatMoney } from './formatMoney';
export { htmlTemplateDecode } from './htmlTemplateDecode';
export { randomColor, randomNum, randomPhone, randomName } from './random';
export { isLeapYear, remainTime, isSameDay } from './date';
export { deepClone } from './deepClone';
export { sum } from './sum';
export { toFixed } from './toFixed';
export { parseQueryString, stringfyQueryString } from './urlQuery';
export { isColor, isEmail, isIdCard, isPhoneNum, isUrl, isMobile, isAppleDevice, isObject, isFunction, isString, isBoolean, isNumber, isUndef, } from './verify';
